#! /bin/bash

source ../Libraries/rules/foamVersion

wmake funkySetFields

wmake funkySetBoundaryField

wmake replayTransientBC

if [[ "$FOAM_DEV" != "" || ( ${WM_PROJECT_VERSION:0:1} == "v" && ${WM_PROJECT_VERSION:1} -gt 1707 ) ]]
then
    wmake funkySetAreaFields
fi

wmake funkyDoCalc

wmake calcNonUniformOffsetsForMapped

wmake fieldReport

wmake funkyPythonPostproc

if [[ "$OPENFOAM_ORG" != "" && $(( $OPENFOAM_ORG > 8 )) ]];
then
    echo "funkySetLagrangianField are not supported for foundation release $OPENFOAM_ORG"
else
    wmake funkySetLagrangianField
fi

wmake funkyWarpMesh

wmake makeAxialMesh

wmake writeBoundarySubfields
